discord:
  token: longrandomstring # see https://discord.com/developers/
  id: bignumber
saucenao:
  enabled: false
  token: longrandomstring # see https://saucenao.com/user.php
syncplay:
  enabled: false
  instances:
  - host: http://localhost:8995
    room: example
    name: syncbot
    # password: optional