instances:
- host: http://localhost:8995
  room: example
  name: syncbot
  # password: optional
  webhooks:
  - url: https://discord.com/api/webhooks/example
    type: DISCORD # available: [matrix, discord]