name: Crystal CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 test:
  runs-on: ubuntu-latest
  steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Install nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09

    - name: run tests
      run: | 
        nix-shell --arg testing true

        pushd spec/test_certs
        ./create_certs.sh
        popd

        crystal spec
        crystal tool format --check