name: Crystal CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 test:
  runs-on: ubuntu-latest
  steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Install nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - name: Enable Build Cache
      uses: cachix/cachix-action@v9
      with:
        name: crystal-ci

    - name: Create Test Certs
      run: |
        pushd spec/test_certs
        ./create_certs.sh
        popd

    - name: Build Release
      run: nix-build

    - name: Upload release artifacts
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/syncplay_bot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      