name: release

on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Set env
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Install dependencies
      run: shards install
    - name: Build Release
      run: |
          mkdir -p dist/
          crystal build src/syncplay_bot.cr -o dist/syncplay_bot

    - name: Upload release artifacts
      uses: softprops/action-gh-release@v1
      with:
        files: dist/syncplay_bot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}